//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PG5_PRACTICA1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        public int codigo { get; set; }
        public string nombre { get; set; }
        public decimal salario_bruto { get; set; }
        public decimal salario_neto { get; set; }
        public decimal deducciones { get; set; }
    }
}
